/**
 * AOT generator — scans source files for class strings and emits a static
 * full-string → record lookup table. Combined with `createTw(prebuilt)` this
 * makes known class strings an O(1) lookup with zero runtime parsing.
 *
 * This module is Node-only (uses `node:fs` / `node:path`) and is not part of
 * the browser entry — it is consumed by the `tw-generate` CLI.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { resolveClasses } from './interpreter'
import type { TwStyle } from './types'

/** Regexes that capture candidate class strings from source text. */
const PATTERNS: RegExp[] = [
  /\btw\(\s*["'`]([^"'`]+)["'`]\s*\)/g, // tw("...")
  /\bclassName\s*=\s*["'`]([^"'`]+)["'`]/g, // className="..."
  /\bclass\s*=\s*["'`]([^"'`]+)["'`]/g, // class="..."
  /\bclass\s*:\s*["'`]([^"'`]+)["'`]/g // class: "..."
]

/** Extract candidate class strings from a source file's text. */
export function extractClassStrings(source: string): string[] {
  const out: string[] = []
  for (const re of PATTERNS) {
    re.lastIndex = 0
    let m: RegExpExecArray | null
    while ((m = re.exec(source)) !== null) {
      const classes = m[1].trim()
      if (classes) out.push(classes)
    }
  }
  return out
}

/** Directories / files never scanned. */
const IGNORED_DIRS = new Set(['node_modules', 'dist', 'build', '.git', '.next', '.nuxt', 'coverage', '.yarn', '.pnp'])

const DEFAULT_EXTENSIONS = new Set(['ts', 'tsx', 'js', 'jsx', 'html', 'vue', 'svelte', 'mdx'])

function isIgnoredDir(name: string): boolean {
  return IGNORED_DIRS.has(name)
}

function walk(dir: string, extensions: Set<string>, out: string[]): void {
  let entries: string[]
  try {
    entries = readdirSync(dir)
  } catch {
    return
  }
  for (const name of entries) {
    if (isIgnoredDir(name)) continue
    const full = join(dir, name)
    let st
    try {
      st = statSync(full)
    } catch {
      continue
    }
    if (st.isDirectory()) {
      walk(full, extensions, out)
    } else if (st.isFile()) {
      const dot = name.lastIndexOf('.')
      const ext = dot >= 0 ? name.slice(dot + 1) : ''
      if (extensions.has(ext)) out.push(full)
    }
  }
}

/**
 * Scan directories for source files and collect every candidate class string.
 */
export function scanClassStrings(
  dirs: string[],
  extensions: string[] = [...DEFAULT_EXTENSIONS]
): { file: string; classes: string[] }[] {
  // An explicitly-passed empty array means "use the defaults" (the CLI passes
  // `[]` when `--extensions` is omitted).
  const extSet = new Set(extensions.length > 0 ? extensions : DEFAULT_EXTENSIONS)
  const results: { file: string; classes: string[] }[] = []
  for (const dir of dirs) {
    const files: string[] = []
    walk(dir, extSet, files)
    for (const file of files) {
      let source: string
      try {
        source = readFileSync(file, 'utf8')
      } catch {
        continue
      }
      const classes = extractClassStrings(source)
      if (classes.length > 0) results.push({ file: relative(process.cwd(), file), classes })
    }
  }
  return results
}

/**
 * Resolve a set of class strings into a full-string → record table.
 * Later occurrences of the same string reuse the same resolved record.
 * Strings that resolve to an empty record (comment noise, unknown tokens)
 * are dropped.
 */
export function generateTable(classStrings: string[]): Record<string, TwStyle> {
  const table: Record<string, TwStyle> = {}
  for (const classes of classStrings) {
    if (classes in table) continue
    const record = resolveClasses(classes)
    if (Object.keys(record).length === 0) continue
    table[classes] = record
  }
  return table
}

/** Serialize a style record as a compact TS object literal. */
function literal(value: unknown): string {
  if (typeof value === 'string') return JSON.stringify(value)
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return String(value)
  return 'undefined'
}

function recordLiteral(record: TwStyle): string {
  const keys = Object.keys(record)
  if (keys.length === 0) return '{}'
  const body = keys.map((k) => `${k}: ${literal(record[k as keyof TwStyle])}`).join(', ')
  return `{ ${body} }`
}

/**
 * Emit the generated TypeScript module content.
 *
 * @param table - full-string → record table
 * @param sourceFiles - scanned files (for the header comment)
 */
export function emitGeneratedFile(table: Record<string, TwStyle>, sourceFiles: string[]): string {
  const lines: string[] = []
  lines.push('// Generated by @rasenjs/tw tw-generate — do not edit manually.')
  lines.push(`// Scanned ${sourceFiles.length} file(s). Re-run: tw-generate --scan <dirs> --out <file>`)
  lines.push('')
  lines.push("import { createTw, type TwStyle } from '@rasenjs/tw'")
  lines.push('')
  lines.push('export const TABLE: Record<string, TwStyle> = {')
  for (const [classes, record] of Object.entries(table)) {
    lines.push(`  ${JSON.stringify(classes)}: ${recordLiteral(record)},`)
  }
  lines.push('}')
  lines.push('')
  lines.push('export const tw = createTw(TABLE)')
  lines.push('')
  return lines.join('\n')
}